# Generated by Django 4.0.5 on 2022-06-29 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='CartMenu',
        ),
    ]
