# Generated by Django 4.0.5 on 2022-07-01 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0004_cafe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='date',
        ),
    ]
