# Generated by Django 4.0.5 on 2022-07-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0005_remove_menu_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
